version: '3.8'

services:
  laravel:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - fastapi
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your-generated-key
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite

  fastapi:
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./fastapi-app:/app